name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Fix paths in HTML
        run: |
          # Ensure all paths in index.html point to the correct location
          sed -i 's|src="/src/|src="/dd-app-v1/src/|g' dist/index.html
          sed -i 's|href="/|href="/dd-app-v1/|g' dist/index.html
          sed -i 's|src="/|src="/dd-app-v1/|g' dist/index.html
          # Don't modify external URLs
          sed -i 's|src="/dd-app-v1/https:|src="https:|g' dist/index.html
          sed -i 's|href="/dd-app-v1/https:|href="https:|g' dist/index.html
          sed -i 's|href="/dd-app-v1/http:|href="http:|g' dist/index.html
          cat dist/index.html

      - name: Copy 404.html for SPA routing
        run: |
          if [ -f "public/404.html" ]; then
            cp public/404.html dist/
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true 