name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to GitHub Pages
        run: |
          chmod +x ./direct-deploy.sh
          ./direct-deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 